use_default_settings: false

server:
  secret_key: "CAMBIA_QUESTA_CHIAVE_LUNGA_RANDOM"
  limiter: true
  public_instance: false

valkey:
  url: "valkey://valkey:6379/0"

search:
  formats:
    - html
    - json

engines:
  - name: bing news
    engine: bing_news
    shortcut: bin
    categories: [news]
    disabled: false

  - name: brave.news
    engine: brave
    shortcut: brnews
    categories: [news]
    disabled: false
